# ===================================
# Kas Kita Backend - Application Config
# ===================================

server.port=8080
spring.application.name=kas-kita-backend

# Logging
logging.level.com.kaskita=DEBUG
logging.level.org.springframework.security=INFO

# Telegram Bot Configuration
telegram.bot.token=8805731441:AAEtMXhL07WI2XesMAHYzeM8yM55_-zrT8Y
telegram.bot.username=kasing_bot

